### PR TITLE
Allow loading discs and tapes from data embedded in the URI. Also allow # instead of ? for query strings: no reason to pass this information to the server.

### PR DESCRIPTION
**Pull request by hexwab**
Test with 

#disc=data:UEsDBBQAAAAIAOEKlkxfovpswwAAAAAKAAAIABwAc3VuZi5zc2RVVAkAA+bV21ru1dtadXgLAAEE9AEAAAToAwAAY2CAAEUnf/8QBQWV4FA/BSBQYRhBgEXAAEj+/8/JcICZge95QyvDGaaBdhO9AC8DF9trA14Gfo4QVduJvAwiiu+NjHWMjEx0zAx0jExNwRjIhEJeBjmh90BBSx0zEwNrU0Mja14GDaHHCp62hjsMDQwMOoz0THgZjGRcbA3NtLZ5Wr1RcNGa7anjorXV0+o90FReBhvWt7wMbmzvgcwAzo8TdUNUef8PoP+dPfSUgGleiXcA3TAKRsEoGAWjYBTQGwAAUEsBAh4DFAAAAAgA4QqWTF+i+mzDAAAAAAoAAAgAGAAAAAAAAAAAALSBAAAAAHN1bmYuc3NkVVQFAAPm1dtadXgLAAEE9AEAAAToAwAAUEsFBgAAAAABAAEATgAAAAUBAAAAAA%3D%3D&autoboot

and 

#tape=data:UEsDBBQAAAAIAJcDZDbbvxZnCAMAAHwGAAALABwAcHVnd2FzaC51ZWZVVAkAA74S6kV1s2xcdXgLAAEE9AEAAAToAwAArVJNaBNBFJ5UKyKsiC2CFxm3mZJNduP+5HfSLWw2m3jpD01DwVPbZOsPtYhafxCh6k1EaIXiUeihNBREwUtBkB57Vi9WUC89eBCtwVOIb3abbZo2VsE32Znvfe/NmzffpGBlcfbipH0aHUEIHYfPvGqPXbdLePw2Ttv2uHUZIZ8P+PIxXxssr9p2uHfOIB8GPzhYyI0Y+bMInazVumZqNYixNIRycxw6cgL/xMGdxqHOLRYPTp+/OXbtAnbYU3vmBvL4a5x+f5gUo0LqtRJRUvyD+rbh6Smbh0isRUSRxbiQ4ufEBuM5pHbib6qWSqiympKdwaGeDlz5RX9ccffT6gKHsu2YQ4OH8CcOnWOwdPQjridwaOrdF0VURNkZijNisihFRElhP0WVxeSN0dFRV62ewy3U8tXVWn4h07Rf502cwfA0OWzgdBGXsD3BUxP4KJgC5q5sjoEBimgq83lqQVYCLA7mrmxOgsWNREKLspmnGchSVC0Sj4aNcCIWDoeTPB0mepKmiR6jm4Zf7Ce0f2BEn6V9RJdpgegLdIjoaRKKBBczfvGN6RcVQeDQrceVjT7So8uQ10dCGt1YMv1vuxWmxRCRAnkiDREhWCAgCAVeFZUZcPIkBBAoqLxcIF7tlysrK65aeiu12upq3as0dELzjd1ZLgearUIYOgoViMDEWYXIkuW4HLo/6TQtwV1NopsOgBY1aN0pFVhMQy3DqSUFFgHwXbzQKwvQu8CaZwrBF+onwWFCK9XZXvDoJnb1qxogcwn+g/Qzhx49X8dZKLxj0sTdnCriIkMGQ1kPOdxEU9RcW1vbR60DdbUuvWf7zOZJ24OD0jmGLIZMDzmc0bUrzKH5uf9yOW1rm9PBBONshkoMFRmCw+tbct4hhrfPqOdw6Nniulu1YeqQJGkftQ7W1fpwlxVsrsC4EjvE9l7DQaXtiznyGNuw2DKe8zSwPNTEOdpnGLLYpcpP/lLmf+Baaj1fLpe31cqiPdRqR91ohqn1tPqnl4lB2SlblLlaPJVKuTUHlN9QSwECHgMUAAAACACXA2Q2278WZwgDAAB8BgAACwAYAAAAAAAAAAAApIEAAAAAcHVnd2FzaC51ZWZVVAUAA74S6kV1eAsAAQT0AQAABOgDAABQSwUGAAAAAAEAAQBRAAAATQMAAAAA&autochain

### CODE REVIEW

**Comment by BigEd** [comment]
(looks like a lint fail:
./main.js: line 729, col 21, 'discImage' is already defined.
)

**Comment by mattgodbolt** [comment]
The linter has been problematic recently. That's not @hexwab 's fault.

**Comment by lurkio** [comment]
How do you convert a .SSD to a data URI? Does it have to be zipped?

**Comment by hexwab** [comment]
Yes, it has to be zipped.  Filename within the zip file is unimportant.
    `zip file.zip file.ssd`
    `echo -n 'https://bbc.godbolt.org/#disc=data:';base64 -w0 file.zip;echo '&autoboot'`

**Pull request merged**
